// glb-doctor.js -- diagnose & fix white (untextured) models
// Auto-generated by setup_models script -- do not edit by hand.
const fs = require('fs');
const path = require('path');
const os = require('os');

const modelsRoot = path.resolve(process.argv[2] || path.join(__dirname, 'models'));
const cacheRoot = path.join(os.tmpdir(), 'kenney_downloads');

function walk(dir, exts, out) {
  out = out || [];
  if (!fs.existsSync(dir)) return out;
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) walk(p, exts, out);
    else if (exts.indexOf(path.extname(e.name).toLowerCase()) >= 0) out.push(p);
  }
  return out;
}

function parseGlbJson(file) {
  const buf = fs.readFileSync(file);
  if (buf.length < 20 || buf.readUInt32LE(0) !== 0x46546c67) return null;
  const jsonLen = buf.readUInt32LE(12);
  return JSON.parse(buf.toString('utf8', 20, 20 + jsonLen));
}

const texExts = ['.png', '.jpg', '.jpeg', '.webp', '.bin'];
const cacheFiles = walk(cacheRoot, texExts);
const cacheByName = new Map();
for (const f of cacheFiles) {
  const n = path.basename(f).toLowerCase();
  if (!cacheByName.has(n)) cacheByName.set(n, f);
}

const glbs = walk(modelsRoot, ['.glb']);
console.log('scanning ' + glbs.length + ' glb file(s) under ' + modelsRoot);
console.log('------------------------------------------------------------');

let okEmbedded = 0, fixed = 0, missing = 0;

for (const glb of glbs) {
  const rel = path.relative(modelsRoot, glb);
  let json;
  try { json = parseGlbJson(glb); } catch (e) {
    console.log('[error] ' + rel + ': cannot parse (' + e.message + ')');
    continue;
  }
  const images = json.images || [];
  const external = images.filter(function(i) { return i.uri && i.uri.indexOf('data:') !== 0; });
  if (external.length === 0) { okEmbedded++; continue; }
  for (const img of external) {
    const uri = decodeURIComponent(img.uri);
    const expected = path.resolve(path.dirname(glb), uri);
    const base = path.basename(uri).toLowerCase();
    if (fs.existsSync(expected)) continue;
    const src = cacheByName.get(base);
    if (src) {
      fs.mkdirSync(path.dirname(expected), { recursive: true });
      fs.copyFileSync(src, expected);
      console.log('[FIXED] ' + rel + ': copied ' + path.basename(src));
      fixed++;
    } else {
      console.log('[MISS]  ' + rel + ': needs "' + uri + '"');
      missing++;
    }
  }
}
console.log('------------------------------------------------------------');
console.log('embedded-ok: ' + okEmbedded + ' | fixed: ' + fixed + ' | still-missing: ' + missing);
