# ============================================================
# phase 2 models v7 (Windows) -- MAX "eggy" style
# v7: new monster trio (panda/pig/bee) + TEXTURE WELD step:
#     reads each monster's .mtl, finds its PNG, embeds it into
#     the GLB via @gltf-transform (fixes white/untextured look)
# characters -> Quaternius Cute Animated Monsters (CC0)
# Put this script in the SAME models folder as characters\ etc.
# ============================================================

$ErrorActionPreference = 'Continue'
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
$UA = @{ 'User-Agent' = 'Mozilla/5.0 (model-setup-phase2)' }

if ((Split-Path $PSScriptRoot -Leaf) -ieq 'models') {
    $modelsRoot = $PSScriptRoot
} else {
    $modelsRoot = Join-Path $PSScriptRoot 'models'
}
$work = Join-Path $env:TEMP 'kenney_downloads'

New-Item -ItemType Directory -Force -Path $work | Out-Null
New-Item -ItemType Directory -Force -Path $modelsRoot | Out-Null
'characters', 'room', 'park' | ForEach-Object {
    New-Item -ItemType Directory -Force -Path (Join-Path $modelsRoot $_) | Out-Null
}
Write-Host "[OK] folders ready: $modelsRoot\{characters, room, park}" -ForegroundColor Green

$hasNode = $null -ne (Get-Command npx -ErrorAction SilentlyContinue)
if ($hasNode) {
    Write-Host "[OK] Node.js found, model conversion available" -ForegroundColor Green
} else {
    Write-Host "[info] Node.js not found; conversion disabled" -ForegroundColor Yellow
}

# ---------- generate glb-doctor.js ----------

$doctorPath = Join-Path $PSScriptRoot 'glb-doctor.js'
$doctorJs = @'
// glb-doctor.js -- diagnose & fix white (untextured) models
const fs = require('fs');
const path = require('path');
const os = require('os');
const modelsRoot = path.resolve(process.argv[2] || path.join(__dirname, 'models'));
const cacheRoot = path.join(os.tmpdir(), 'kenney_downloads');
function walk(dir, exts, out) {
  out = out || [];
  if (!fs.existsSync(dir)) return out;
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) walk(p, exts, out);
    else if (exts.indexOf(path.extname(e.name).toLowerCase()) >= 0) out.push(p);
  }
  return out;
}
function parseGlbJson(file) {
  const buf = fs.readFileSync(file);
  if (buf.length < 20 || buf.readUInt32LE(0) !== 0x46546c67) return null;
  const jsonLen = buf.readUInt32LE(12);
  return JSON.parse(buf.toString('utf8', 20, 20 + jsonLen));
}
const cacheFiles = walk(cacheRoot, ['.png', '.jpg', '.jpeg', '.webp', '.bin']);
const cacheByName = new Map();
for (const f of cacheFiles) {
  const n = path.basename(f).toLowerCase();
  if (!cacheByName.has(n)) cacheByName.set(n, f);
}
const glbs = walk(modelsRoot, ['.glb']);
console.log('scanning ' + glbs.length + ' glb file(s)');
let okEmbedded = 0, fixed = 0, missing = 0;
for (const glb of glbs) {
  const rel = path.relative(modelsRoot, glb);
  let json;
  try { json = parseGlbJson(glb); } catch (e) { continue; }
  const images = json.images || [];
  const external = images.filter(function(i) { return i.uri && i.uri.indexOf('data:') !== 0; });
  if (external.length === 0) { okEmbedded++; continue; }
  for (const img of external) {
    const uri = decodeURIComponent(img.uri);
    const expected = path.resolve(path.dirname(glb), uri);
    const base = path.basename(uri).toLowerCase();
    if (fs.existsSync(expected)) continue;
    const src = cacheByName.get(base);
    if (src) {
      fs.mkdirSync(path.dirname(expected), { recursive: true });
      fs.copyFileSync(src, expected);
      console.log('[FIXED] ' + rel + ': copied ' + path.basename(src));
      fixed++;
    } else {
      console.log('[MISS]  ' + rel + ': needs "' + uri + '"');
      missing++;
    }
  }
}
console.log('embedded-ok: ' + okEmbedded + ' | fixed: ' + fixed + ' | still-missing: ' + missing);
'@
Set-Content -Path $doctorPath -Value $doctorJs -Encoding ASCII

# ---------- generate fix-monster-textures.js ----------

$fixJsPath = Join-Path $PSScriptRoot 'fix-monster-textures.js'
$fixJs = @'
// fix-monster-textures.js -- weld PNG textures into OBJ-converted
// GLBs (obj2gltf drops external textures -> models look white).
// Auto-generated by setup_models script.
// args: <toolDir> <modelsRoot> <cacheRoot> <mapFile>
const fs = require('fs');
const path = require('path');

const toolDir = process.argv[2];
const modelsRoot = process.argv[3];
const cacheRoot = process.argv[4];
const mapFile = process.argv[5];

const { NodeIO } = require(path.join(toolDir, 'node_modules', '@gltf-transform', 'core'));

function walk(dir, exts, out) {
  out = out || [];
  if (!fs.existsSync(dir)) return out;
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) walk(p, exts, out);
    else if (exts.indexOf(path.extname(e.name).toLowerCase()) >= 0) out.push(p);
  }
  return out;
}

const cacheFiles = walk(cacheRoot, ['.mtl', '.png', '.jpg', '.jpeg']);
const byName = new Map();
for (const f of cacheFiles) {
  const n = path.basename(f).toLowerCase();
  if (!byName.has(n)) byName.set(n, f);
}

const io = new NodeIO();
const map = JSON.parse(fs.readFileSync(mapFile, 'utf8'));

(async function() {
  for (const rel of Object.keys(map)) {
    const base = map[rel];
    const glb = path.join(modelsRoot, rel);
    if (!fs.existsSync(glb)) { console.log('[skip] ' + rel + ' (glb not found)'); continue; }
    let doc;
    try { doc = await io.read(glb); } catch (e) { console.log('[skip] ' + rel + ': ' + e.message); continue; }
    if (doc.getRoot().listTextures().length > 0) { console.log('[ok] ' + rel + ' already textured'); continue; }

    // 1) ask the .mtl which texture the model wants
    let texFile = null;
    const mtl = byName.get((base + '.mtl').toLowerCase());
    if (mtl) {
      const c = fs.readFileSync(mtl, 'utf8');
      const m = c.match(/^\s*map_Kd\s+(.+)$/mi);
      if (m) {
        const want = path.basename(m[1].trim()).toLowerCase();
        texFile = byName.get(want) || null;
      }
    }
    // 2) fuzzy: any png whose name contains the monster name
    if (!texFile) {
      for (const entry of byName) {
        const n = entry[0];
        if (n.endsWith('.png') && n.indexOf(base.toLowerCase()) >= 0) { texFile = entry[1]; break; }
      }
    }
    if (!texFile) { console.log('[MISS] ' + rel + ': no texture found for ' + base); continue; }

    const tex = doc.createTexture(path.basename(texFile))
      .setImage(fs.readFileSync(texFile))
      .setMimeType('image/png');
    const mats = doc.getRoot().listMaterials();
    for (const mat of mats) { mat.setBaseColorTexture(tex); }
    await io.write(glb, doc);
    console.log('[FIXED] ' + rel + ' <- ' + path.basename(texFile) + ' (' + mats.length + ' material(s))');
  }
})().catch(function(e) { console.log('[error] ' + e.message); });
'@
Set-Content -Path $fixJsPath -Value $fixJs -Encoding ASCII
Write-Host "[OK] helper scripts generated" -ForegroundColor Green

# ---------- helpers ----------

function Download-Zip-Extract($url, $dir) {
    $zip = Join-Path $env:TEMP ((Split-Path $dir -Leaf) + '.zip')
    Invoke-WebRequest -Uri $url -OutFile $zip -UseBasicParsing -Headers $UA
    Expand-Archive -Path $zip -DestinationPath $dir -Force
    Remove-Item $zip -Force
}

function Try-OpenGameArt($name, $pageUrl, $directUrl) {
    $dir = Join-Path $work $name
    if (Test-Path $dir) { return $dir }
    $candidates = @()
    if ($directUrl) { $candidates += $directUrl }
    try {
        $html = (Invoke-WebRequest -Uri $pageUrl -UseBasicParsing -Headers $UA -TimeoutSec 30).Content
        $hits = [regex]::Matches($html, 'https?://opengameart\.org/sites/default/files/[^"<>\s]+\.zip')
        foreach ($h in $hits) { $candidates += $h.Value }
    } catch {}
    foreach ($u in ($candidates | Select-Object -Unique)) {
        try {
            Write-Host "[ downloading ] $name (opengameart) ..." -ForegroundColor Cyan
            Download-Zip-Extract $u $dir
            Write-Host "[done] $name (opengameart)" -ForegroundColor Green
            return $dir
        } catch {}
    }
    return $null
}

function Try-GitHubArchive($name, $repo) {
    $dir = Join-Path $work $name
    if (Test-Path $dir) { return $dir }
    foreach ($branch in @('main','master')) {
        try {
            Write-Host "[ downloading ] $name (github: $repo @$branch) ..." -ForegroundColor Cyan
            Download-Zip-Extract "https://github.com/$repo/archive/refs/heads/$branch.zip" $dir
            Write-Host "[done] $name (github archive)" -ForegroundColor Green
            return $dir
        } catch {}
    }
    return $null
}

function Get-PackModels($packDir) {
    if (-not $packDir) { return @() }
    foreach ($ext in @('*.glb','*.gltf','*.fbx','*.obj')) {
        $found = @(Get-ChildItem -Path $packDir -Recurse -Filter $ext -ErrorAction SilentlyContinue)
        if ($found.Count -gt 0) { return @($found | Sort-Object Name) }
    }
    return @()
}

function Pick-Model($models, $patterns, $exclude) {
    foreach ($pat in $patterns) {
        $hit = $models | Where-Object { $_.Name -like $pat -and ($exclude -notcontains $_.FullName) } |
               Select-Object -First 1
        if ($hit) { return $hit }
    }
    return $null
}

function Convert-GltfToGlb($gltfFile, $outGlb) {
    if (-not $script:hasNode) { return $false }
    Push-Location $gltfFile.DirectoryName
    & npx --yes gltf-pipeline -i $gltfFile.FullName -o $outGlb 2>&1 | Out-Null
    Pop-Location
    return (Test-Path $outGlb)
}

function Convert-FbxToGlb($fbxFile, $outGlb) {
    if (-not $script:hasNode) { return $false }
    Push-Location $fbxFile.DirectoryName
    $out = & npx --yes fbx2gltf -i $fbxFile.FullName -o $outGlb -b 2>&1 | Out-String
    Pop-Location
    if ((Test-Path "$outGlb.glb") -and -not (Test-Path $outGlb)) {
        Move-Item "$outGlb.glb" $outGlb -Force
    }
    if (Test-Path $outGlb) { return $true }
    return $false
}

function Convert-ObjToGlb($objFile, $outGlb) {
    if (-not $script:hasNode) { return $false }
    Push-Location $objFile.DirectoryName
    & npx --yes obj2gltf -i $objFile.FullName -o $outGlb 2>&1 | Out-Null
    Pop-Location
    return (Test-Path $outGlb)
}

$placed = @()
$missing = @()
$monMap = @{}

function Place-Model($file, $relPath, $models) {
    if (-not $file) {
        $script:missing += $relPath
        Write-Host "[MISS] $relPath (no matching model; app uses fallback shape)" -ForegroundColor Red
        return
    }
    $dest = Join-Path $modelsRoot $relPath
    New-Item -ItemType Directory -Force -Path (Split-Path $dest) | Out-Null
    $ext = $file.Extension.ToLower()
    if ($ext -eq '.glb') {
        Copy-Item $file.FullName $dest -Force
    } else {
        Write-Host "[convert] $($file.Name) -> glb ..." -ForegroundColor Cyan
        $okConv = $false
        switch ($ext) {
            '.gltf' { $okConv = Convert-GltfToGlb $file $dest }
            '.fbx'  {
                $okConv = Convert-FbxToGlb $file $dest
                if (-not $okConv) {
                    $objAlt = Get-ChildItem -Path $work -Recurse -Filter ($file.BaseName + '.obj') -ErrorAction SilentlyContinue |
                              Select-Object -First 1
                    if ($objAlt) {
                        Write-Host "[retry] $($objAlt.Name) via obj2gltf ..." -ForegroundColor Cyan
                        $okConv = Convert-ObjToGlb $objAlt $dest
                    }
                }
            }
            '.obj'  { $okConv = Convert-ObjToGlb $file $dest }
        }
        if (-not $okConv) {
            $script:missing += $relPath
            Write-Host "[MISS] $relPath (conversion failed)" -ForegroundColor Red
            return
        }
    }
    $script:placed += "$relPath   from   $($file.Name)"
    Write-Host "[OK] $relPath   from   $($file.Name)" -ForegroundColor Green
}

# ---------- 1. download packs ----------

Write-Host ""
Write-Host "===== downloading packs =====" -ForegroundColor Magenta

$monPack  = Try-OpenGameArt 'quaternius-cute-monsters' `
    'https://opengameart.org/content/textured-cute-monster-pack' `
    'https://opengameart.org/sites/default/files/cute_animated_monsters_-_aug_2020.zip'
$furnPack = Try-GitHubArchive 'kaykit-furniture'    'KayKit-Game-Assets/KayKit-Furniture-Bits-1.0'
$restPack = Try-GitHubArchive 'kaykit-restaurant'   'KayKit-Game-Assets/KayKit-Restaurant-Bits-1.0'
$cityPack = Try-GitHubArchive 'kaykit-city-builder' 'KayKit-Game-Assets/KayKit-City-Builder-Bits-1.0'
$foodPack = Try-OpenGameArt 'kenney-food-kit' `
    'https://opengameart.org/content/food-kit' `
    'https://opengameart.org/sites/default/files/kenney_food-kit.zip'

$monModels  = Get-PackModels $monPack
$furnModels = Get-PackModels $furnPack
$restModels = Get-PackModels $restPack
$cityModels = Get-PackModels $cityPack
$foodModels = Get-PackModels $foodPack

$roomModels = @($furnModels) + @($restModels)
$allModels  = @($roomModels) + @($cityModels) + @($foodModels) + @($monModels)

# ---------- 2. characters (cute monsters, new trio) ----------

Write-Host ""
Write-Host "===== characters/ (MAX eggy: cute monsters) =====" -ForegroundColor Magenta

if ($monModels.Count -eq 0) {
    Write-Host "[info] monster pack unavailable, keeping current characters" -ForegroundColor Yellow
} else {
    $names = ($monModels | Select-Object -First 25 | ForEach-Object { $_.Name }) -join ', '
    Write-Host "[info] monsters available: $names" -ForegroundColor DarkCyan

    $chosen = @()
    $meFile = Pick-Model $monModels @('*panda*','*penguin*') $chosen
    if ($meFile) { $chosen += $meFile.FullName }
    $friendFile = Pick-Model $monModels @('*pig*','*chicken*') $chosen
    if ($friendFile) { $chosen += $friendFile.FullName }
    $helperFile = Pick-Model $monModels @('*bee*','*crab*','*turtle*') $chosen
    if ($helperFile) { $chosen += $helperFile.FullName }
    $rest = @($monModels | Where-Object { $chosen -notcontains $_.FullName })
    if (-not $meFile -and $rest.Count -ge 1)     { $meFile = $rest[0];     if ($rest.Count -gt 1) { $rest = $rest[1..($rest.Count-1)] } }
    if (-not $friendFile -and $rest.Count -ge 1) { $friendFile = $rest[0]; if ($rest.Count -gt 1) { $rest = $rest[1..($rest.Count-1)] } }
    if (-not $helperFile -and $rest.Count -ge 1) { $helperFile = $rest[0] }

    Place-Model $meFile     'characters/me.glb' $monModels
    Place-Model $friendFile 'characters/friend.glb' $monModels
    Place-Model $helperFile 'characters/helper.glb' $monModels

    if ($meFile)     { $monMap['characters/me.glb'] = $meFile.BaseName }
    if ($friendFile) { $monMap['characters/friend.glb'] = $friendFile.BaseName }
    if ($helperFile) { $monMap['characters/helper.glb'] = $helperFile.BaseName }
}

# ---------- 3. room/ ----------

Write-Host ""
Write-Host "===== room/ =====" -ForegroundColor Magenta

Place-Model (Pick-Model $roomModels @('*couch*pillow*','*couch*','*sofa*','*lounge*') @()) 'room/sofa.glb' $roomModels
Place-Model (Pick-Model $roomModels @('*wardrobe*','*cabinet*tall*','*cabinet*decorated*','*cabinet*medium*','*cabinet*','*dresser*','*closet*') @()) 'room/cabinet.glb' $roomModels

$noLamp = @($roomModels | Where-Object { $_.Name -notlike '*lamp*' })
$desk = Pick-Model $noLamp @('*desk*','*table*square*','*table*round_B*','*table*long*','*table*') @()
Place-Model $desk 'room/desk.glb' $noLamp

Place-Model (Pick-Model $roomModels @('*chair_A.glb','*chair_A.*','*chair*a*','*chair*') @()) 'room/chair.glb' $roomModels

$tableExclude = @(); if ($desk) { $tableExclude = @($desk.FullName) }
Place-Model (Pick-Model $noLamp @('*table*coffee*','*table*round*','*dining*table*','*table*') $tableExclude) 'room/table.glb' $noLamp

Place-Model (Pick-Model $roomModels @('*bed*single*','*bed*double*','*bed*') @()) 'room/bed.glb' $roomModels
Place-Model (Pick-Model $roomModels @('*stove*','*oven*','*cooker*','*fridge*') @()) 'room/stove.glb' $roomModels
Place-Model (Pick-Model $roomModels @('*book*set*','*books*','*book*') @()) 'room/books.glb' $roomModels
Place-Model (Pick-Model $allModels  @('*backpack*','*school*bag*','*paperbag*','*bag*','*sack*') @()) 'room/bag.glb' $allModels
Place-Model (Pick-Model (@($roomModels) + @($foodModels)) @('*cup*','*mug*','*glass*','*bottle*') @()) 'room/cup.glb' $roomModels

# ---------- 4. park/ ----------

Write-Host ""
Write-Host "===== park/ =====" -ForegroundColor Magenta

Place-Model (Pick-Model $allModels @('*bench*','*picnic*') @()) 'park/bench.glb' $allModels
$duckFile = Pick-Model $monModels @('*duck*','*chicken*','*penguin*','*bird*') @()
Place-Model $duckFile 'park/duck.glb' $monModels
if ($duckFile) { $monMap['park/duck.glb'] = $duckFile.BaseName }

# ---------- 5. texture check + monster texture weld ----------

Write-Host ""
Write-Host "===== texture check =====" -ForegroundColor Magenta

if (Get-Command node -ErrorAction SilentlyContinue) {
    & node $doctorPath $modelsRoot
}

Write-Host ""
Write-Host "===== monster texture weld =====" -ForegroundColor Magenta

if ($monMap.Count -eq 0) {
    Write-Host "[info] no monster models to weld" -ForegroundColor Yellow
} elseif (-not (Get-Command npm -ErrorAction SilentlyContinue)) {
    Write-Host "[info] npm not found, skipping texture weld" -ForegroundColor Yellow
} else {
    $toolDir = Join-Path $work '_glbtool'
    if (-not (Test-Path (Join-Path $toolDir 'node_modules\@gltf-transform\core\package.json'))) {
        Write-Host "[setup] installing @gltf-transform/core (one time) ..." -ForegroundColor Cyan
        New-Item -ItemType Directory -Force -Path $toolDir | Out-Null
        Push-Location $toolDir
        if (-not (Test-Path 'package.json')) { & npm init -y 2>&1 | Out-Null }
        & npm i @gltf-transform/core --no-fund --no-audit --loglevel=error 2>&1 | Out-Null
        Pop-Location
    }
    $mapFile = Join-Path $work 'monmap.json'
    ($monMap | ConvertTo-Json) | Set-Content $mapFile -Encoding ASCII
    & node $fixJsPath $toolDir $modelsRoot $work $mapFile
}

# ---------- 6. summary ----------

Write-Host ""
Write-Host "============================================================" -ForegroundColor Green
Write-Host " PHASE 2 v7 DONE. models root: $modelsRoot"
Write-Host "------------------------------------------------------------"
Write-Host " Placed $($placed.Count) file(s):"
$placed | ForEach-Object { Write-Host "   $_" }
if ($missing.Count -gt 0) {
    Write-Host " Missing $($missing.Count):" -ForegroundColor Yellow
    $missing | ForEach-Object { Write-Host "   $_" -ForegroundColor Yellow }
}
Write-Host "------------------------------------------------------------"
Write-Host " New trio: panda / pig / bee (from 21-monster pack)."
Write-Host " Want different ones? Tell the assistant which from the list:"
Write-Host " Alien, Bat, Cactus, Chicken, Crab, Cthulhu, Cyclops, Deer,"
Write-Host " Demon, Ghost, GreenDemon, Panda, Penguin, Pig, Skull, Tree,"
Write-Host " YellowDragon, Yeti, Bee, Mushroom, Alien_Tall"
Write-Host " Hard-refresh browser (Ctrl+F5)!"
Write-Host "============================================================"