# ============================================================
# shop scene models: download + rename + organize (Windows) v8
# v8: glb-doctor.js is now GENERATED by this script (pure ASCII)
#     so a corrupted hand-copied file can never break it again
# Sources (all CC0, commercial OK, no attribution)
# Run: double-click the .bat next to this file
# ============================================================

$ErrorActionPreference = 'Continue'
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
$UA = @{ 'User-Agent' = 'Mozilla/5.0 (model-setup-script)' }

if ((Split-Path $PSScriptRoot -Leaf) -ieq 'models') {
    $modelsRoot = $PSScriptRoot
} else {
    $modelsRoot = Join-Path $PSScriptRoot 'models'
}
$work = Join-Path $env:TEMP 'kenney_downloads'

New-Item -ItemType Directory -Force -Path $work | Out-Null
New-Item -ItemType Directory -Force -Path $modelsRoot | Out-Null
'characters', 'street', 'shop' | ForEach-Object {
    New-Item -ItemType Directory -Force -Path (Join-Path $modelsRoot $_) | Out-Null
}
Write-Host "[OK] folders ready: $modelsRoot\{characters, street, shop}" -ForegroundColor Green

$hasNode = $null -ne (Get-Command npx -ErrorAction SilentlyContinue)
if ($hasNode) {
    Write-Host "[OK] Node.js found, gltf->glb conversion available" -ForegroundColor Green
} else {
    Write-Host "[info] Node.js not found; .gltf models cannot be auto-converted" -ForegroundColor Yellow
}

# ---------- generate glb-doctor.js (always fresh, pure ASCII) ----------

$doctorPath = Join-Path $PSScriptRoot 'glb-doctor.js'
$doctorJs = @'
// glb-doctor.js -- diagnose & fix white (untextured) models
// Auto-generated by setup_models.ps1 -- do not edit by hand.
// Usage: node glb-doctor.js [modelsDir]
const fs = require('fs');
const path = require('path');
const os = require('os');

const modelsRoot = path.resolve(process.argv[2] || path.join(__dirname, 'models'));
const cacheRoot = path.join(os.tmpdir(), 'kenney_downloads');

function walk(dir, exts, out) {
  out = out || [];
  if (!fs.existsSync(dir)) return out;
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) walk(p, exts, out);
    else if (exts.indexOf(path.extname(e.name).toLowerCase()) >= 0) out.push(p);
  }
  return out;
}

function parseGlbJson(file) {
  const buf = fs.readFileSync(file);
  if (buf.length < 20 || buf.readUInt32LE(0) !== 0x46546c67) return null;
  const jsonLen = buf.readUInt32LE(12);
  return JSON.parse(buf.toString('utf8', 20, 20 + jsonLen));
}

const texExts = ['.png', '.jpg', '.jpeg', '.webp', '.bin'];
const cacheFiles = walk(cacheRoot, texExts);
const cacheByName = new Map();
for (const f of cacheFiles) {
  const n = path.basename(f).toLowerCase();
  if (!cacheByName.has(n)) cacheByName.set(n, f);
}

const glbs = walk(modelsRoot, ['.glb']);
console.log('scanning ' + glbs.length + ' glb file(s) under ' + modelsRoot);
console.log('cache: ' + cacheFiles.length + ' texture/bin file(s) indexed in ' + cacheRoot);
console.log('------------------------------------------------------------');

let okEmbedded = 0, fixed = 0, missing = 0, noImages = 0;

for (const glb of glbs) {
  const rel = path.relative(modelsRoot, glb);
  let json;
  try { json = parseGlbJson(glb); } catch (e) {
    console.log('[error] ' + rel + ': cannot parse (' + e.message + ')');
    continue;
  }
  const images = json.images || [];
  if (images.length === 0) {
    console.log('[plain] ' + rel + ': no textures (uses plain colors)');
    noImages++;
    continue;
  }
  const external = images.filter(function(i) { return i.uri && i.uri.indexOf('data:') !== 0; });
  if (external.length === 0) {
    console.log('[ok]    ' + rel + ': ' + images.length + ' texture(s) embedded');
    okEmbedded++;
    continue;
  }
  for (const img of external) {
    const uri = decodeURIComponent(img.uri);
    const expected = path.resolve(path.dirname(glb), uri);
    const base = path.basename(uri).toLowerCase();
    if (fs.existsSync(expected)) {
      console.log('[ok]    ' + rel + ': ' + uri + ' already present');
      continue;
    }
    const src = cacheByName.get(base);
    if (src) {
      fs.mkdirSync(path.dirname(expected), { recursive: true });
      fs.copyFileSync(src, expected);
      console.log('[FIXED] ' + rel + ': copied ' + path.basename(src) + ' -> ' + path.relative(modelsRoot, expected));
      fixed++;
    } else {
      console.log('[MISS]  ' + rel + ': needs "' + uri + '" but it was not found in cache');
      missing++;
    }
  }
}

console.log('------------------------------------------------------------');
console.log('embedded-ok: ' + okEmbedded + ' | plain-color: ' + noImages + ' | fixed: ' + fixed + ' | still-missing: ' + missing);
if (missing > 0) {
  console.log('tip: rerun setup_models.ps1 (it now downloads texture PNGs too),');
  console.log('or download the pack in a browser and copy the PNG it asks for.');
}
console.log('NOTE: hard-refresh the browser (Ctrl+F5) after fixing, to bypass cache.');
'@
Set-Content -Path $doctorPath -Value $doctorJs -Encoding ASCII
Write-Host "[OK] glb-doctor.js generated" -ForegroundColor Green

# ---------- helpers ----------

function Download-Zip-Extract($url, $dir) {
    $zip = Join-Path $env:TEMP ((Split-Path $dir -Leaf) + '.zip')
    Invoke-WebRequest -Uri $url -OutFile $zip -UseBasicParsing -Headers $UA
    Expand-Archive -Path $zip -DestinationPath $dir -Force
    Remove-Item $zip -Force
}

function Try-Kenney($name, $pageUrl) {
    $dir = Join-Path $work $name
    if (Test-Path $dir) { return $dir }
    try {
        $html = (Invoke-WebRequest -Uri $pageUrl -UseBasicParsing -Headers $UA -TimeoutSec 20).Content
        $m = [regex]::Match($html, 'href="([^"]+\.zip)"')
        if ($m.Success) {
            $href = $m.Groups[1].Value
            if ($href -notmatch '^https?://') { $href = 'https://kenney.nl' + $href }
            Download-Zip-Extract $href $dir
            Write-Host "[done] $name (kenney.nl)" -ForegroundColor Green
            return $dir
        }
    } catch {}
    return $null
}

function Try-OpenGameArt($name, $pageUrl, $directUrl) {
    $dir = Join-Path $work $name
    if (Test-Path $dir) { return $dir }
    $candidates = @()
    try {
        $html = (Invoke-WebRequest -Uri $pageUrl -UseBasicParsing -Headers $UA -TimeoutSec 30).Content
        $hits = [regex]::Matches($html, 'https?://opengameart\.org/sites/default/files/[^"<>\s]+\.zip')
        foreach ($h in $hits) { $candidates += $h.Value }
    } catch {}
    if ($directUrl) { $candidates += $directUrl }
    foreach ($u in ($candidates | Select-Object -Unique)) {
        try {
            Write-Host "[ downloading ] $name (opengameart) ..." -ForegroundColor Cyan
            Download-Zip-Extract $u $dir
            Write-Host "[done] $name (opengameart)" -ForegroundColor Green
            return $dir
        } catch {}
    }
    return $null
}

# Download model files AND their texture files from a GitHub repo folder
function Try-GitHubTreeFiles($name, $repo, $pathFilter) {
    $dir = Join-Path $work $name
    if (Test-Path $dir) { return $dir }
    try {
        Write-Host "[ downloading ] $name (github tree: $repo, filter: $pathFilter) ..." -ForegroundColor Cyan
        $repoInfo = Invoke-RestMethod -Uri "https://api.github.com/repos/$repo" -Headers $UA -TimeoutSec 30
        $branch = $repoInfo.default_branch
        $tree = Invoke-RestMethod -Uri "https://api.github.com/repos/$repo/git/trees/${branch}?recursive=1" -Headers $UA -TimeoutSec 60
        $files = @($tree.tree | Where-Object {
            $_.type -eq 'blob' -and $_.path -like "*$pathFilter*" -and
            ($_.path -match '\.(glb|png|jpg|jpeg|webp)$')
        })
        if (($files | Where-Object { $_.path -like '*.glb' }).Count -eq 0) {
            Write-Host "[info] no glb found under filter '$pathFilter' in $repo" -ForegroundColor Yellow
            return $null
        }
        New-Item -ItemType Directory -Force -Path $dir | Out-Null
        foreach ($f in $files) {
            $raw = "https://raw.githubusercontent.com/$repo/$branch/" + ($f.path -replace ' ', '%20')
            Invoke-WebRequest -Uri $raw -OutFile (Join-Path $dir (Split-Path $f.path -Leaf)) -UseBasicParsing -Headers $UA -TimeoutSec 60
        }
        Write-Host "[done] $name ($($files.Count) files incl. textures)" -ForegroundColor Green
        return $dir
    } catch {
        Write-Host "[info] github tree failed for $repo : $($_.Exception.Message)" -ForegroundColor Yellow
        return $null
    }
}

function Try-GitHubArchive($name, $repo) {
    $dir = Join-Path $work $name
    if (Test-Path $dir) { return $dir }
    foreach ($branch in @('main','master')) {
        try {
            Write-Host "[ downloading ] $name (github: $repo @$branch) ..." -ForegroundColor Cyan
            Download-Zip-Extract "https://github.com/$repo/archive/refs/heads/$branch.zip" $dir
            Write-Host "[done] $name (github archive)" -ForegroundColor Green
            return $dir
        } catch {}
    }
    return $null
}

# Collect models: .glb preferred, .gltf as convertible fallback
function Get-PackModels($packDir) {
    if (-not $packDir) { return @() }
    $glb  = @(Get-ChildItem -Path $packDir -Recurse -Filter '*.glb'  -ErrorAction SilentlyContinue)
    $gltf = @(Get-ChildItem -Path $packDir -Recurse -Filter '*.gltf' -ErrorAction SilentlyContinue)
    if ($glb.Count -gt 0) { return @($glb | Sort-Object Name) }
    return @($gltf | Sort-Object Name)
}

function Pick-Model($models, $patterns, $exclude) {
    foreach ($pat in $patterns) {
        $hit = $models | Where-Object { $_.Name -like $pat -and ($exclude -notcontains $_.FullName) } |
               Select-Object -First 1
        if ($hit) { return $hit }
    }
    return $null
}

# Convert .gltf -> .glb via gltf-pipeline (needs Node.js); run in the
# model's own folder so relative .bin/texture references resolve
function Convert-ToGlb($gltfFile, $outGlb) {
    if (-not $script:hasNode) { return $false }
    try {
        Push-Location $gltfFile.DirectoryName
        & npx --yes gltf-pipeline -i $gltfFile.FullName -o $outGlb 2>&1 | Out-Null
        Pop-Location
        return (Test-Path $outGlb)
    } catch {
        Pop-Location
        return $false
    }
}

$placed = @()
$missing = @()

function Place-Model($file, $relPath, $models) {
    if (-not $file) {
        $script:missing += $relPath
        Write-Host "[MISS] $relPath (no matching model found)" -ForegroundColor Red
        if ($models -and $models.Count -gt 0) {
            $names = ($models | Select-Object -First 30 | ForEach-Object { $_.Name }) -join ', '
            Write-Host "       available in pack: $names" -ForegroundColor DarkYellow
        }
        return
    }
    $dest = Join-Path $modelsRoot $relPath
    New-Item -ItemType Directory -Force -Path (Split-Path $dest) | Out-Null
    if ($file.Extension -ieq '.glb') {
        Copy-Item $file.FullName $dest -Force
    } else {
        Write-Host "[convert] $($file.Name) -> glb ..." -ForegroundColor Cyan
        if (-not (Convert-ToGlb $file $dest)) {
            $script:missing += $relPath
            Write-Host "[MISS] $relPath (conversion failed; install Node.js from nodejs.org and rerun)" -ForegroundColor Red
            return
        }
    }
    $script:placed += "$relPath   from   $($file.Name)"
    Write-Host "[OK] $relPath   from   $($file.Name)" -ForegroundColor Green
}

# ---------- 1. characters (Kenney Blocky Characters) ----------

Write-Host ""
Write-Host "===== characters pack =====" -ForegroundColor Magenta

$charPack = Try-Kenney 'blocky-characters' 'https://kenney.nl/assets/blocky-characters'
if (-not $charPack) {
    $charPack = Try-OpenGameArt 'blocky-characters' `
        'https://opengameart.org/content/blocky-characters' `
        'https://opengameart.org/sites/default/files/kenney_blocky-characters_2.0.zip'
}

$charModels = Get-PackModels $charPack
$people = @($charModels | Where-Object { $_.Name -notmatch 'anim' })
if ($people.Count -ge 3) {
    Place-Model $people[0] 'characters/me.glb' $charModels
    Place-Model $people[1] 'characters/friend.glb' $charModels
    Place-Model $people[2] 'characters/helper.glb' $charModels
} else {
    Write-Host "[WARN] less than 3 character models found" -ForegroundColor Red
    $missing += 'characters/me.glb','characters/friend.glb','characters/helper.glb'
}

# ---------- 2. street (Kenney City Kit Suburban, incl. textures) ----------

Write-Host ""
Write-Host "===== street pack =====" -ForegroundColor Magenta

$cityPack = Try-Kenney 'city-kit-suburban' 'https://kenney.nl/assets/city-kit-suburban'
if (-not $cityPack) {
    $cityPack = Try-GitHubTreeFiles 'city-kit-suburban' 'null3d-engine/sample-assets' 'kenney-suburban'
}

$cityModels = Get-PackModels $cityPack

$b1 = Pick-Model $cityModels @('*house*type01*','*house*type1.glb','*house_a*','*building*type*a*','*house*','*building*') @()
Place-Model $b1 'street/building_1.glb' $cityModels

$b2exclude = @(); if ($b1) { $b2exclude = @($b1.FullName) }
$b2 = Pick-Model $cityModels @('*house*type05*','*house*type5.glb','*house_b*','*building*type*b*','*house*','*building*') $b2exclude
Place-Model $b2 'street/building_2.glb' $cityModels

$t1 = Pick-Model $cityModels @('*tree*large*','*tree*big*','*tree*') @()
Place-Model $t1 'street/tree_1.glb' $cityModels

$t2exclude = @(); if ($t1) { $t2exclude = @($t1.FullName) }
$t2 = Pick-Model $cityModels @('*tree*small*','*tree*little*','*tree*') $t2exclude
Place-Model $t2 'street/tree_2.glb' $cityModels

# ---------- 3. shop (Furniture + Restaurant Bits combined) ----------

Write-Host ""
Write-Host "===== shop pack =====" -ForegroundColor Magenta

$furnPack = Try-Kenney 'furniture-kit' 'https://kenney.nl/assets/furniture-kit'
if (-not $furnPack) {
    $furnPack = Try-GitHubArchive 'kaykit-furniture' 'KayKit-Game-Assets/KayKit-Furniture-Bits-1.0'
}
$restPack = Try-GitHubArchive 'kaykit-restaurant' 'KayKit-Game-Assets/KayKit-Restaurant-Bits-1.0'

$furnModels = Get-PackModels $furnPack
$restModels = Get-PackModels $restPack
$shopModels = @($furnModels) + @($restModels)

Place-Model (Pick-Model $shopModels @('*bookcase*open*','*bookcase*','*bookshelf*','*shelf*','*rack*') @()) 'shop/shelf.glb' $shopModels
Place-Model (Pick-Model $shopModels @('*kitchen*bar*','*counter*','*kitchen*cabinet*','*cabinet*medium*','*cabinet*','*bar*','*desk*','*stove*') @()) 'shop/counter.glb' $shopModels
Place-Model (Pick-Model $shopModels @('*cardboard*','*crate*','*box*','*package*','*barrel*','*sack*','*paperbag*','*bag*') @()) 'shop/crate.glb' $shopModels
Place-Model (Pick-Model $shopModels @('*potted*plant*','*plant*pot*','*plant*','*cactus*medium*','*cactus*','*flower*pot*','*flower*') @()) 'shop/plant.glb' $shopModels

# ---------- 4. fix external textures (white models) ----------

Write-Host ""
Write-Host "===== texture check (fix white models) =====" -ForegroundColor Magenta

if (Get-Command node -ErrorAction SilentlyContinue) {
    & node $doctorPath $modelsRoot
} else {
    Write-Host "[info] node not found, skipping texture check" -ForegroundColor Yellow
}

# ---------- 5. summary ----------

Write-Host ""
Write-Host "============================================================" -ForegroundColor Green
Write-Host " DONE. models root: $modelsRoot"
Write-Host "------------------------------------------------------------"
Write-Host " Placed $($placed.Count) file(s):"
$placed | ForEach-Object { Write-Host "   $_" }
if ($missing.Count -gt 0) {
    Write-Host " Missing $($missing.Count) (app still runs with fallback shapes):" -ForegroundColor Yellow
    $missing | ForEach-Object { Write-Host "   $_" -ForegroundColor Yellow }
    Write-Host " Manual pick folder: $work"
    Write-Host " Or download from: https://kenney.nl/assets (browser works)"
}
Write-Host "------------------------------------------------------------"
Write-Host " IMPORTANT: hard-refresh the browser (Ctrl+F5) to see textures"
Write-Host " Preview: scene-lab.html?stage=3d&debug=1"
Write-Host "============================================================"