# ============================================================
# phase 2 models v3 (Windows) -- "eggy" cute style
# v3: ALSO replaces characters with KayKit chibi characters
#     (round eggy style, 75 animations, textures embedded)
# Creates/overwrites:
#   models/characters/{me,friend,helper}.glb   <- KayKit (NEW)
#   models/room/{sofa,cabinet,desk,chair,table,bed,stove,
#                books,bag,cup}.glb
#   models/park/{bench,duck}.glb
# All CC0, commercial OK, no attribution.
# IMPORTANT: put this script in the SAME models folder that
# already contains characters\ street\ shop\ from phase 1!
# ============================================================

$ErrorActionPreference = 'Continue'
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
$UA = @{ 'User-Agent' = 'Mozilla/5.0 (model-setup-phase2)' }

if ((Split-Path $PSScriptRoot -Leaf) -ieq 'models') {
    $modelsRoot = $PSScriptRoot
} else {
    $modelsRoot = Join-Path $PSScriptRoot 'models'
}
$work = Join-Path $env:TEMP 'kenney_downloads'

if (-not (Test-Path (Join-Path $modelsRoot 'characters'))) {
    Write-Host "[WARN] no characters\ folder found in $modelsRoot" -ForegroundColor Red
    Write-Host "       This script must sit in the SAME models folder as phase 1" -ForegroundColor Red
    Write-Host "       (the one containing characters\, street\, shop\)." -ForegroundColor Red
}

New-Item -ItemType Directory -Force -Path $work | Out-Null
New-Item -ItemType Directory -Force -Path $modelsRoot | Out-Null
'characters', 'room', 'park' | ForEach-Object {
    New-Item -ItemType Directory -Force -Path (Join-Path $modelsRoot $_) | Out-Null
}
Write-Host "[OK] folders ready: $modelsRoot\{characters, room, park}" -ForegroundColor Green

$hasNode = $null -ne (Get-Command npx -ErrorAction SilentlyContinue)
if ($hasNode) {
    Write-Host "[OK] Node.js found, gltf->glb conversion available" -ForegroundColor Green
} else {
    Write-Host "[info] Node.js not found; .gltf models cannot be auto-converted" -ForegroundColor Yellow
}

# ---------- generate glb-doctor.js ----------

$doctorPath = Join-Path $PSScriptRoot 'glb-doctor.js'
$doctorJs = @'
// glb-doctor.js -- diagnose & fix white (untextured) models
// Auto-generated by setup_models script -- do not edit by hand.
const fs = require('fs');
const path = require('path');
const os = require('os');

const modelsRoot = path.resolve(process.argv[2] || path.join(__dirname, 'models'));
const cacheRoot = path.join(os.tmpdir(), 'kenney_downloads');

function walk(dir, exts, out) {
  out = out || [];
  if (!fs.existsSync(dir)) return out;
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) walk(p, exts, out);
    else if (exts.indexOf(path.extname(e.name).toLowerCase()) >= 0) out.push(p);
  }
  return out;
}

function parseGlbJson(file) {
  const buf = fs.readFileSync(file);
  if (buf.length < 20 || buf.readUInt32LE(0) !== 0x46546c67) return null;
  const jsonLen = buf.readUInt32LE(12);
  return JSON.parse(buf.toString('utf8', 20, 20 + jsonLen));
}

const texExts = ['.png', '.jpg', '.jpeg', '.webp', '.bin'];
const cacheFiles = walk(cacheRoot, texExts);
const cacheByName = new Map();
for (const f of cacheFiles) {
  const n = path.basename(f).toLowerCase();
  if (!cacheByName.has(n)) cacheByName.set(n, f);
}

const glbs = walk(modelsRoot, ['.glb']);
console.log('scanning ' + glbs.length + ' glb file(s) under ' + modelsRoot);
console.log('------------------------------------------------------------');

let okEmbedded = 0, fixed = 0, missing = 0;

for (const glb of glbs) {
  const rel = path.relative(modelsRoot, glb);
  let json;
  try { json = parseGlbJson(glb); } catch (e) {
    console.log('[error] ' + rel + ': cannot parse (' + e.message + ')');
    continue;
  }
  const images = json.images || [];
  const external = images.filter(function(i) { return i.uri && i.uri.indexOf('data:') !== 0; });
  if (external.length === 0) { okEmbedded++; continue; }
  for (const img of external) {
    const uri = decodeURIComponent(img.uri);
    const expected = path.resolve(path.dirname(glb), uri);
    const base = path.basename(uri).toLowerCase();
    if (fs.existsSync(expected)) continue;
    const src = cacheByName.get(base);
    if (src) {
      fs.mkdirSync(path.dirname(expected), { recursive: true });
      fs.copyFileSync(src, expected);
      console.log('[FIXED] ' + rel + ': copied ' + path.basename(src));
      fixed++;
    } else {
      console.log('[MISS]  ' + rel + ': needs "' + uri + '"');
      missing++;
    }
  }
}
console.log('------------------------------------------------------------');
console.log('embedded-ok: ' + okEmbedded + ' | fixed: ' + fixed + ' | still-missing: ' + missing);
'@
Set-Content -Path $doctorPath -Value $doctorJs -Encoding ASCII
Write-Host "[OK] glb-doctor.js generated" -ForegroundColor Green

# ---------- helpers ----------

function Download-Zip-Extract($url, $dir) {
    $zip = Join-Path $env:TEMP ((Split-Path $dir -Leaf) + '.zip')
    Invoke-WebRequest -Uri $url -OutFile $zip -UseBasicParsing -Headers $UA
    Expand-Archive -Path $zip -DestinationPath $dir -Force
    Remove-Item $zip -Force
}

function Try-ScrapeZip($name, $pageUrl, $domain) {
    $dir = Join-Path $work $name
    if (Test-Path $dir) { return $dir }
    try {
        $html = (Invoke-WebRequest -Uri $pageUrl -UseBasicParsing -Headers $UA -TimeoutSec 20).Content
        $m = [regex]::Match($html, 'href="([^"]+\.zip)"')
        if ($m.Success) {
            $href = $m.Groups[1].Value
            if ($href -notmatch '^https?://') { $href = $domain + $href }
            Download-Zip-Extract $href $dir
            Write-Host "[done] $name ($domain)" -ForegroundColor Green
            return $dir
        }
    } catch {}
    return $null
}

function Try-OpenGameArt($name, $pageUrl, $directUrl) {
    $dir = Join-Path $work $name
    if (Test-Path $dir) { return $dir }
    $candidates = @()
    if ($directUrl) { $candidates += $directUrl }
    try {
        $html = (Invoke-WebRequest -Uri $pageUrl -UseBasicParsing -Headers $UA -TimeoutSec 30).Content
        $hits = [regex]::Matches($html, 'https?://opengameart\.org/sites/default/files/[^"<>\s]+\.zip')
        foreach ($h in $hits) { $candidates += $h.Value }
    } catch {}
    foreach ($u in ($candidates | Select-Object -Unique)) {
        try {
            Write-Host "[ downloading ] $name (opengameart) ..." -ForegroundColor Cyan
            Download-Zip-Extract $u $dir
            Write-Host "[done] $name (opengameart)" -ForegroundColor Green
            return $dir
        } catch {}
    }
    return $null
}

function Try-GitHubArchive($name, $repo) {
    $dir = Join-Path $work $name
    if (Test-Path $dir) { return $dir }
    foreach ($branch in @('main','master')) {
        try {
            Write-Host "[ downloading ] $name (github: $repo @$branch) ..." -ForegroundColor Cyan
            Download-Zip-Extract "https://github.com/$repo/archive/refs/heads/$branch.zip" $dir
            Write-Host "[done] $name (github archive)" -ForegroundColor Green
            return $dir
        } catch {}
    }
    return $null
}

function Get-PackModels($packDir) {
    if (-not $packDir) { return @() }
    $glb  = @(Get-ChildItem -Path $packDir -Recurse -Filter '*.glb'  -ErrorAction SilentlyContinue)
    $gltf = @(Get-ChildItem -Path $packDir -Recurse -Filter '*.gltf' -ErrorAction SilentlyContinue)
    if ($glb.Count -gt 0) { return @($glb | Sort-Object Name) }
    return @($gltf | Sort-Object Name)
}

function Pick-Model($models, $patterns, $exclude) {
    foreach ($pat in $patterns) {
        $hit = $models | Where-Object { $_.Name -like $pat -and ($exclude -notcontains $_.FullName) } |
               Select-Object -First 1
        if ($hit) { return $hit }
    }
    return $null
}

function Convert-ToGlb($gltfFile, $outGlb) {
    if (-not $script:hasNode) { return $false }
    try {
        Push-Location $gltfFile.DirectoryName
        & npx --yes gltf-pipeline -i $gltfFile.FullName -o $outGlb 2>&1 | Out-Null
        Pop-Location
        return (Test-Path $outGlb)
    } catch {
        Pop-Location
        return $false
    }
}

$placed = @()
$missing = @()

function Place-Model($file, $relPath, $models) {
    if (-not $file) {
        $script:missing += $relPath
        Write-Host "[MISS] $relPath (no matching model; app uses fallback shape)" -ForegroundColor Red
        return
    }
    $dest = Join-Path $modelsRoot $relPath
    New-Item -ItemType Directory -Force -Path (Split-Path $dest) | Out-Null
    if ($file.Extension -ieq '.glb') {
        Copy-Item $file.FullName $dest -Force
    } else {
        Write-Host "[convert] $($file.Name) -> glb ..." -ForegroundColor Cyan
        if (-not (Convert-ToGlb $file $dest)) {
            $script:missing += $relPath
            Write-Host "[MISS] $relPath (conversion failed)" -ForegroundColor Red
            return
        }
    }
    $script:placed += "$relPath   from   $($file.Name)"
    Write-Host "[OK] $relPath   from   $($file.Name)" -ForegroundColor Green
}

# ---------- 1. download packs ----------

Write-Host ""
Write-Host "===== downloading packs =====" -ForegroundColor Magenta

$charPack = Try-GitHubArchive 'kaykit-characters'   'KayKit-Game-Assets/KayKit-Character-Pack-Adventures-1.0'
$furnPack = Try-GitHubArchive 'kaykit-furniture'    'KayKit-Game-Assets/KayKit-Furniture-Bits-1.0'
$restPack = Try-GitHubArchive 'kaykit-restaurant'   'KayKit-Game-Assets/KayKit-Restaurant-Bits-1.0'
$cityPack = Try-GitHubArchive 'kaykit-city-builder' 'KayKit-Game-Assets/KayKit-City-Builder-Bits-1.0'
$foodPack = Try-OpenGameArt 'kenney-food-kit' `
    'https://opengameart.org/content/food-kit' `
    'https://opengameart.org/sites/default/files/kenney_food-kit.zip'
$animPack = Try-ScrapeZip 'quaternius-animals' 'https://quaternius.com/packs/ultimateanimatedanimals.html' 'https://quaternius.com'

$charModels = Get-PackModels $charPack
$furnModels = Get-PackModels $furnPack
$restModels = Get-PackModels $restPack
$cityModels = Get-PackModels $cityPack
$foodModels = Get-PackModels $foodPack
$animModels = Get-PackModels $animPack

$roomModels = @($furnModels) + @($restModels)
$allModels  = @($roomModels) + @($cityModels) + @($foodModels) + @($animModels)

# ---------- 2. characters (KayKit chibi, textures embedded) ----------

Write-Host ""
Write-Host "===== characters/ (eggy style) =====" -ForegroundColor Magenta

# pack contains Barbarian / Knight / Mage / Rogue / Rogue_Hooded
$knight = Pick-Model $charModels @('*knight*') @()
$mage   = Pick-Model $charModels @('*mage*','*wizard*') @()
$rogue  = Pick-Model $charModels @('*rogue.glb','*rogue_hooded*','*rogue*') @()
$barb   = Pick-Model $charModels @('*barbarian*') @()

# me = knight (fallback barbarian), friend = rogue, helper = mage
$meFile = $knight; if (-not $meFile) { $meFile = $barb }
if (-not $meFile -and $charModels.Count -ge 1) { $meFile = $charModels[0] }
$friendFile = $rogue
if (-not $friendFile) { $friendFile = $charModels | Where-Object { $_.FullName -ne $meFile.FullName } | Select-Object -First 1 }
$helperFile = $mage
if (-not $helperFile) { $helperFile = $charModels | Where-Object { $_.FullName -ne $meFile.FullName -and $_.FullName -ne $friendFile.FullName } | Select-Object -First 1 }

Place-Model $meFile     'characters/me.glb' $charModels
Place-Model $friendFile 'characters/friend.glb' $charModels
Place-Model $helperFile 'characters/helper.glb' $charModels

# ---------- 3. room/ ----------

Write-Host ""
Write-Host "===== room/ =====" -ForegroundColor Magenta

Place-Model (Pick-Model $roomModels @('*couch*pillow*','*couch*','*sofa*','*lounge*') @()) 'room/sofa.glb' $roomModels
Place-Model (Pick-Model $roomModels @('*wardrobe*','*cabinet*tall*','*cabinet*decorated*','*cabinet*medium*','*cabinet*','*dresser*','*closet*') @()) 'room/cabinet.glb' $roomModels

# desk: furniture pack has no real desk; never grab a lamp
$noLamp = @($roomModels | Where-Object { $_.Name -notlike '*lamp*' })
$desk = Pick-Model $noLamp @('*desk*','*table*square*','*table*round_B*','*table*long*','*table*') @()
Place-Model $desk 'room/desk.glb' $noLamp

Place-Model (Pick-Model $roomModels @('*chair_A.glb','*chair_A.*','*chair*a*','*chair*') @()) 'room/chair.glb' $roomModels

$tableExclude = @(); if ($desk) { $tableExclude = @($desk.FullName) }
Place-Model (Pick-Model $noLamp @('*table*coffee*','*table*round*','*dining*table*','*table*') $tableExclude) 'room/table.glb' $noLamp

Place-Model (Pick-Model $roomModels @('*bed*single*','*bed*double*','*bed*') @()) 'room/bed.glb' $roomModels
Place-Model (Pick-Model $roomModels @('*stove*','*oven*','*cooker*','*fridge*') @()) 'room/stove.glb' $roomModels
Place-Model (Pick-Model $roomModels @('*book*set*','*books*','*book*') @()) 'room/books.glb' $roomModels
Place-Model (Pick-Model $allModels  @('*backpack*','*school*bag*','*paperbag*','*bag*','*sack*') @()) 'room/bag.glb' $allModels
Place-Model (Pick-Model (@($roomModels) + @($foodModels)) @('*cup*','*mug*','*glass*','*bottle*') @()) 'room/cup.glb' $roomModels

# ---------- 4. park/ ----------

Write-Host ""
Write-Host "===== park/ =====" -ForegroundColor Magenta

Place-Model (Pick-Model $allModels @('*bench*','*picnic*') @()) 'park/bench.glb' $allModels
Place-Model (Pick-Model $animModels @('*duck*','*goose*','*chicken*','*bird*') @()) 'park/duck.glb' $animModels

# ---------- 5. texture check ----------

Write-Host ""
Write-Host "===== texture check =====" -ForegroundColor Magenta

if (Get-Command node -ErrorAction SilentlyContinue) {
    & node $doctorPath $modelsRoot
} else {
    Write-Host "[info] node not found, skipping texture check" -ForegroundColor Yellow
}

# ---------- 6. summary ----------

Write-Host ""
Write-Host "============================================================" -ForegroundColor Green
Write-Host " PHASE 2 v3 DONE. models root: $modelsRoot"
Write-Host "------------------------------------------------------------"
Write-Host " Placed $($placed.Count) file(s):"
$placed | ForEach-Object { Write-Host "   $_" }
if ($missing.Count -gt 0) {
    Write-Host " Missing $($missing.Count) (app still runs with fallback shapes):" -ForegroundColor Yellow
    $missing | ForEach-Object { Write-Host "   $_" -ForegroundColor Yellow }
    Write-Host " Manual options:"
    Write-Host "   bag  -> https://poly.pizza/search/backpack (filter CC0)"
    Write-Host "   duck -> https://poly.pizza/search/duck (filter CC0)"
    Write-Host "   duck -> https://quaternius.com/packs/ultimateanimatedanimals.html (browser)"
}
Write-Host "------------------------------------------------------------"
Write-Host " NOTE: characters are now KayKit chibi style with 75"
Write-Host " animations (idle/walk/wave...) - your code plays them."
Write-Host " Old Kenney characters were overwritten (backup in browser"
Write-Host " cache is gone; re-run phase-1 script to restore if needed)."
Write-Host " Hard-refresh browser (Ctrl+F5)!"
Write-Host "============================================================"